@startuml Domain

class ModelInfo{
	modelId: string
	modelUrl: string
	model: VRM
	isPublished: boolean
	internalUserId: string
}
class User{
	userId: string
	internalUserId: string
}

ModelInfo "0..n" --> "0..1" User
note right of ModelInfo: ・isPublishedは公開・非公開ステータスで、公開からスタートする
note right of User: ・userIdはログインにのみ使用し、モデルとの対応はinternalUserIdを使用する\n・internalUserIdは乱数で生成する

@enduml